CREATE SCHEMA IPL;

SET SEARCH_PATH TO IPL;

CREATE TABLE Players(
    	PlayerID CHARACTER(5) PRIMARY KEY,
	"Name" VARCHAR(50) NOT NULL, 
	Nationality  VARCHAR(50) NOT NULL,
	DoB DATE NOT NULL,
	"Role"  VARCHAR(50),
	StrikeRate DECIMAL(5,2),
	BowlingStyle  VARCHAR(50),
	BattingStyle  VARCHAR(50)
);

CREATE TABLE TitleSponsor(
	CompanyName VARCHAR(50) PRIMARY KEY,
	BusinessDomain VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL	
);
